#!/bin/bash
# this code will print DNS info

digServer (){
	if [ -z "$1" ]; then
		echo "no parameter provided. closing..."
		exit 1
	fi

	ans=$(dig "$1"."$2" | grep -A1 "ANSWER SECTION" | tail -n 1)
	RECORD_TYPE=$(cut -d '\t' -f 3)
	echo "The subdomain [SUB_DOMAIN] is a $RECORD_TYPE record and points to [DESTINATION]"
	return 0
}

# echo "Number of params provided is $#"
if [ $# -lt 1 ]; then
	echo "$0 Usage:
		- domain_name {optional:subdomain}"
	exit 1
fi

if [ $# -gt 1 ]; then
	digServer "$2"."$1"
fi

if [ $# -eq 1 ]; then
	digServer www "$1"
	digServer lb-01 "$1"
	digServer web-01 "$1"
	digServer web-02 "$1"
fi