#!/usr/bin/env bash
#  It retrieves DNS information for a specified domain name
#  and subdomain if provided, and it also provides information
#  for some default subdomains if no subdomain is provided.

digServer (){
	if [ -z "$1" ]; then
		echo "no parameter provided. closing..."
		exit 1
	fi
	domain="$1"."$2"
	ans=$(dig "$domain" | grep -A1 "ANSWER SECTION" | tail -n 1)
	RECORD_TYPE=$(echo "$ans" | awk '{print $4}')
	DESTINATION=$(echo "$ans" | awk '{print $5}')
	echo "The subdomain $1 is a $RECORD_TYPE record and points to $DESTINATION"
	return 0
}

# echo "Number of params provided is $#"
if [ $# -lt 1 ]; then
	echo "$0 Usage:
		- domain_name {optional:subdomain}"
	exit 1
fi

if [ $# -gt 1 ]; then
	digServer "$2"."$1"
fi

if [ $# -eq 1 ]; then
	digServer www "$1"
	digServer lb-01 "$1"
	digServer web-01 "$1"
	digServer web-02 "$1"
fi
