#!/usr/bin/env bash
# transfer file from client to server
#
path="$(cd "$(dirname "${BASH_SOURCE[0]}")")"
filename=$(basename "$BASH_SOURCE")
red='\e[0;44m'
black='\033[0m'
file="$1"
user="$3"
key="$4"
ip="$2"

if [ $# -eq 4 ]; then
	scp -i "$key" -o StrictHostKeyChecking=no "$path"/"$file" "$user"@"$ip":/home/"$user"/
else
	echo -e "Usage: ${red}$filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${black}"
fi
