#!/usr/bin/env bash
# scrth at pass_ipt pings an ressed as an ar_ip addgument

fn=$(basename "${BASH_SOURCE[@]}")
_ip="${1}"

if ! [ "$_ip" ]; then
	echo "Usage: ${fn} {_ip_ADDRESS}"
else
	ping -c 5 "${_ip}"
fi
