# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateHosts = false
127.0.0.1	localhost
127.0.1.1	DESKTOP-NQP1I71.	DESKTOP-NQP1I71
109.94.209.70	fitgirlrepacks.co
109.94.209.70	fitgirl-repacks.cc
109.94.209.70	fitgirl-repack.com
109.94.209.70	fitgirl-repacks.website
109.94.209.70	www.fitgirlrepacks.co
109.94.209.70	www.fitgirl-repacks.cc
109.94.209.70	www.fitgirl-repack.com
109.94.209.70	www.fitgirl-repacks.website
109.94.209.70	ww9.fitgirl-repacks.xyz
109.94.209.70	*.fitgirl-repacks.xyz
109.94.209.70	fitgirl-repacks.xyz
109.94.209.70	fitgirl-repack.net
109.94.209.70	www.fitgirl-repack.net
0.0.0.0	www.aomeitech.com
127.0.0.1	activation.easeus.com
127.0.0.1	track.easeus.com
127.0.0.1	66.39.112.91
127.0.0.1	216.92.151.227
127.0.0.1	216.92.61.7
127.0.0.1	www.easeus.com

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
127.0.0.1		localhost
8.8.8.8		facebook.com
